(shebang) @keyword.directive
(identifier) @variable
(type_identifier) @type
(primitive_type) @type.builtin
(field_identifier) @variable.member
(shorthand_field_identifier) @variable.member
(self) @variable.builtin
"_" @character.special
(crate) @module
(super) @module
"$" @function.macro
(metavariable) @function.macro
(boolean_literal) @boolean
(integer_literal) @number
(float_literal) @number.float
(raw_string_literal) @string
(string_literal) @string
(escape_sequence) @string.escape
(char_literal) @character
"use" @keyword.import
"mod" @keyword.import
"default" @keyword
"impl" @keyword
"let" @keyword
"move" @keyword
"unsafe" @keyword
"where" @keyword
"enum" @keyword.type
"struct" @keyword.type
"union" @keyword.type
"trait" @keyword.type
"type" @keyword.type
"async" @keyword.coroutine
"await" @keyword.coroutine
"gen" @keyword.coroutine
"try" @keyword.exception
"ref" @keyword.modifier
"pub" @keyword.modifier
"raw" @keyword.modifier
(mutable_specifier) @keyword.modifier
"const" @keyword.modifier
"static" @keyword.modifier
"dyn" @keyword.modifier
"extern" @keyword.modifier
"fn" @keyword.function
"return" @keyword.return
"yield" @keyword.return
"if" @keyword.conditional
"else" @keyword.conditional
"match" @keyword.conditional
"break" @keyword.repeat
"continue" @keyword.repeat
"in" @keyword.repeat
"loop" @keyword.repeat
"while" @keyword.repeat
"for" @keyword
"!" @operator
"!=" @operator
"%" @operator
"%=" @operator
"&" @operator
"&&" @operator
"&=" @operator
"*" @operator
"*=" @operator
"+" @operator
"+=" @operator
"-" @operator
"-=" @operator
".." @operator
"..=" @operator
"..." @operator
"/" @operator
"/=" @operator
"<" @operator
"<<" @operator
"<<=" @operator
"<=" @operator
"=" @operator
"==" @operator
">" @operator
">=" @operator
">>" @operator
">>=" @operator
"?" @operator
"@" @operator
"^" @operator
"^=" @operator
"|" @operator
"|=" @operator
"||" @operator
"(" @punctuation.bracket
")" @punctuation.bracket
"[" @punctuation.bracket
"]" @punctuation.bracket
"{" @punctuation.bracket
"}" @punctuation.bracket
"," @punctuation.delimiter
"." @punctuation.delimiter
":" @punctuation.delimiter
"::" @punctuation.delimiter
";" @punctuation.delimiter
"->" @punctuation.delimiter
"=>" @punctuation.delimiter
(line_comment) @comment
(block_comment) @comment
(outer_doc_comment_marker) @comment
(inner_doc_comment_marker) @comment