"@media" @keyword.directive
"@charset" @keyword.directive
"@namespace" @keyword.directive
"@supports" @keyword.directive
"@keyframes" @keyword.directive
(at_keyword) @keyword.directive
"@import" @keyword.import
(to) @keyword
(from) @keyword
(comment) @comment
(tag_name) @tag
(class_name) @type
(id_name) @constant
(property_name) @property
(feature_name) @property
(nesting_selector) @character.special
(universal_selector) @character.special
(function_name) @function
"~" @operator
">" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"=" @operator
"^=" @operator
"|=" @operator
"~=" @operator
"$=" @operator
"*=" @operator
"and" @keyword.operator
"or" @keyword.operator
"not" @keyword.operator
"only" @keyword.operator
(important) @keyword.modifier
(attribute_name) @tag.attribute
(namespace_name) @module
(string_value) @string
(color_value) @string
(unit) @string
(integer_value) @number
(float_value) @number.float
"#" @punctuation.delimiter
"," @punctuation.delimiter.comma
"." @punctuation.delimiter
":" @punctuation.delimiter
"::" @punctuation.delimiter
";" @punctuation.delimiter
"{" @punctuation.bracket.braces
")" @punctuation.bracket.parentheses
"(" @punctuation.bracket.parentheses
"}" @punctuation.bracket.braces
"[" @punctuation.bracket
"]" @punctuation.bracket